### ISSUE TITLE
[Question]: Demo link

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#10]
### What feature would you like to add?

Hi,
Thanks for this awesome package,
Could you please share with us a  demo link same as shown on tutorial videos ? 
I've faced some issues on event crud.
Thanks

**Comment by lukas-frey** [comment]
I'll try to create a demo repo in the coming days.

**Comment by aeq-dev** [comment]
Thanks,
I mean a GitHub repository to check your code examples :)

**Comment by lukas-frey** [comment]
There's now a demo project inside this repository at [/demo](https://github.com/GuavaCZ/calendar-demo/tree/e1f851f845591cec24acbc4214368090c84fedc9)

**Comment by aeq-dev** [comment]
Thank you so much ! you make my month :)))))))
