### ISSUE TITLE
[Help]: Resources

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#11]
### What feature would you like to add?

I'm trying to setup resources, but cannot display events on each resource (Events created but not displayed under their resources).
Here's my setup : 
Models : `Activity` has many `Task`
Task Model : 
```
 public function toEvent(): Event|array
    {
        return Event::make($this)
            ->title($this->title)
            ->start($this->starts_at)
            ->end($this->ends_at)
            ->backgroundColor($this->bg_color ?? 400)
            ->textColor($this->text_color ?? '#ffffff')
            ->extendedProps(['users' => $this->workers])
            ->resourceIds([$this->activity_id]);
    }
```
Activity Model : 
```
public function toResource(): array | Resource
    {
        return Resource::make($this)
            ->title($this->name);
    }

```
CalendarWidget : 
```
public function getOptions(): array
    {
        return [
            'headerToolbar' => [
                'start' => 'title',
                'center' => 'resourceTimeGridDay,dayGridMonth,timeGridWeek,timeGridDay',
                'end' => 'today prev,next',               
            ]
        ];
    }
```

![aaa today](https://github.com/user-attachments/assets/5b866da6-11cf-4182-bc43-77a09d31fcb2)

**Comment by lukas-frey** [comment]
in your Activity model in the `toResource` method, you need to define an ID for the resource, not pass `$this` to the Resource Value Object.

**Comment by lukas-frey** [comment]
In version 1.2.1, passing just `$this` to the Resource should work now and it will use the primary key as the ID for the resource.

**Comment by aeq-dev** [comment]
Thank you so much :))) It works now

**Comment by aeq-dev** [comment]
Hi @lukas-frey 
Let's say we have an event model Task which belongs to User & Activity,
How could we create two resources view one per User & other per Activity ?
Thanks

**Comment by aeq-dev** [comment]
Never mind, just use resourceIds :))))
Sorry :))))
