### ISSUE TITLE
[Bug]: ContextMenuActions 

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#15]
### What happened?

In attached video below, when I click to create or edit an event, the context menu is not on the right position of the cursor; I don't know what I'm missing, same issue using Firefox & chrome

### How to reproduce the bug

Click on the cell to create an event using ContextMenuActions

### Package Version

1.2.1

### PHP Version

8.2

### Laravel Version

10

https://github.com/user-attachments/assets/b71bb053-6e15-42c5-bafd-e79e8ef28d3a

**Comment by lukas-frey** [comment]
You need to have a custom filament theme and add the packages views to the paths to check Tailwind classes for.

**Comment by aeq-dev** [comment]
Thanks a lot dear @lukas-frey awesome package :))))))

**Comment by lukas-frey** [comment]
Thanks, I'm glad you enjoy the package. :)

**Comment by aeq-dev** [comment]
Dear @lukas-frey Could you please provide us paypal method for your donation? I want to send you a gift for this awesome package :))))

**Comment by lukas-frey** [comment]
> Dear @lukas-frey Could you please provide us paypal method for your donation? I want to send you a gift for this awesome package :))))

That's very nice of you :) Yes, you can also use PayPal [here](https://www.paypal.com/donate/?hosted_button_id=L2PE5DYUQGMTQ) via our donation button if you want. Much appreciated! May I ask what is not working with GitHub sponsors?

**Comment by lukas-frey** [comment]
Appreciate it! Ah, yes, GitHub stopped supporting PayPal for some reason in February last year.
