### ISSUE TITLE
[Question]: Edit views title

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#18]
### What feature would you like to add?

Hello,
How could we edit views titles? if we use for example : listDay,listWeek,listMonth views, it will be displayed like this : 
![Screenshot 2024-07-25 at 18-21-20 Calendar - AMA-CAR](https://github.com/user-attachments/assets/873a403d-c467-487a-8bcc-98216b587af3)

**Comment by lukas-frey** [comment]
Hi, override the getOptions method and return an array with your settings according to the buttonText option [here](https://github.com/vkurko/calendar?tab=readme-ov-file#buttontext):

```php
public function getOptions () {
    return [
        'buttonText' => [
            // your settings here
        ]
    ];
}
```

**Comment by aeq-dev** [comment]
Thanks :)

**Comment by Mohammed-800** [comment]
@lukas-frey 
 where Can I write that function?

**Comment by lukas-frey** [comment]
Inside your calendar widget class.

**Comment by Mohammed-800** [comment]
@lukas-frey see 
![image](https://github.com/user-attachments/assets/646f8131-8694-454c-8b7e-341285763339)

**Comment by Mohammed-800** [comment]
@lukas-frey thank you brother 
![image](https://github.com/user-attachments/assets/fadc3558-9fc8-4eda-ba0e-9fe9bc631b9f)

**Comment by aeq-dev** [comment]
Hi @lukas-frey 
How can we make it dynamic ? I want to change it based on some conditions or dependencies

**Comment by lukas-frey** [comment]
You can't. But you can override the Header where `Calendar` is written and render your own Filament Actions there that toggle the view by calling `setOption('view', <new-view>)` on the calendar.

**Comment by aeq-dev** [comment]
Yes I got it ! thank you :))

**Comment by TheChosenOne29** [comment]
> You can't. But you can override the Header title where "Calendar" is written and render your own view with Filament Actions there that toggle the view by calling `setOption('view', <new-view>)` on the calendar.

Sorry, how do you do this exactly? I'm spending way too much time trying to change the "Calendar" in the widget's header. I want to change "Calendar" to let's say "Reservation"

**Comment by lukas-frey** [comment]
> > You can't. But you can override the Header title where "Calendar" is written and render your own view with Filament Actions there that toggle the view by calling `setOption('view', <new-view>)` on the calendar.
> 
> Sorry, how do you do this exactly? I'm spending way too much time trying to change the "Calendar" in the widget's header. I want to change "Calendar" to let's say "Reservation"
> 
If I recall correctly, you'd override `public function getHeading(): HtmlString|string|Closure|null` and return your own html.

> And also the buttons for the Header Actions, can we customize that also?
Yeah, just override `public function getHeaderActions(): array`

**Comment by TheChosenOne29** [comment]
`    
public function getHeading(): HtmlString
    {
        return new HtmlString('Reservasi');
    }

public function getHeaderActions(): array
    {
        return [
            CreateAction::make('createReservation')
                ->model(Reservation::class)
                ->icon('heroicon-o-calendar')
                ->label('Buat Reservasi Baru'),
        ];
    }
`

Thanks mate 🙏 @lukas-frey

**Comment by lukas-frey** [comment]
You're welcome :)
