### ISSUE TITLE
[Request]: Create new event by dragging / clicking inside the calendar

### ISSUE THREAD

**Issue by mwagena** [GuavaCZ/calendar#21]
### What feature would you like to add?

Is it possible to add a feature to trigger a Filament Action by doing the following:
- click on specific hour inside a specific day
- drag from one hour to another hour inside a specific day
- 
<img width="302" alt="Scherm­afbeelding 2024-07-31 om 16 33 42" src="https://github.com/user-attachments/assets/b06d20db-196f-492e-8dde-c151efaea59e">

**Comment by lukas-frey** [comment]
You can open a context menu on [date click](https://github.com/GuavaCZ/calendar?tab=readme-ov-file#date-click-context-menu) or [date select](https://github.com/GuavaCZ/calendar?tab=readme-ov-file#date-select-context-menu).

There you can have any Action you want.

**Comment by lukas-frey** [comment]
Merged in #22
