### ISSUE TITLE
[Request]: Share other data for event.blade.php

### ISSUE THREAD

**Issue by lukacavic** [GuavaCZ/calendar#23]
### What feature would you like to add?

Hi, I have made custom view for event. Like in tutorial, event.blade.php, and I am using data from event object. I show 5 event values for one event. Now when calendar is using dayView it looks good, but when I switch it to monthly or weekly, it looks messed up. 
Is there a way to know for event object what calendar view is selected, so event display can be modified for that view.

**Comment by lukas-frey** [comment]
yes, in the alpine data except the `event` object there should also be a `view` object and view.type contains the type of the view.

**Comment by lukacavic** [comment]
> yes, in the alpine data except the `event` object there should also be a `view` object and view.type contains the type of the view.

Thanks, I will try it

**Comment by lukacavic** [comment]
It is working, thanks!

**Comment by webplusmultimedia** [comment]
+1
yes no view, no timeText datas anymore for Alpine
