### ISSUE TITLE
[Request]: Style resource headers

### ISSUE THREAD

**Issue by lukacavic** [GuavaCZ/calendar#24]
### What feature would you like to add?

Hi, is it possible to add option to modify resource headers, for example to allow HTML, or to set custom view for resource, like for event? 
In this calendar layout resource are little less visible

**Comment by lukas-frey** [comment]
Hi, no not yet possible. I'm willing to accept a PR though, `resourceLabelContent` needs to be implemented in a similar way like `eventContent`.

**Comment by lukas-frey** [comment]
Hi @lukacavic, in v1.5.0 a `getResourceLabelContent` method was added that works similarly to the `getEventContent` method.

The only problem is that vkurko/calendar currently doesn't support adding extendedProps to the resource objects. I've brought this up already in a [discussion here](https://github.com/vkurko/calendar/discussions/310), so feel free to up-vote it if you want to see it added soon.

In the meantime though, there is an easy fix, provided you are adding the widget to a custom filament page. If so, you can simply add the required resource data as alpine x-data on the root of the page, such as:


```php
<x-filament-panels::page
x-data="{
    resources: {{json_encode($this->getEventResources())}}
}"
>
</x-filament-panels::page>
```

where `getEventResources()` is a method in your custom filament page, where you return a key => value array, where the `key` is the ID of the resource and the `value` is the data you want to pass for each resource (either a simple value or an array if you want to pass multiple data per resource).

Then in your resource label content view, you can simply access this data using alpine, like `resources[resource.id].<your-custom-data-here>`.

**Comment by lukas-frey** [comment]
Hi! Version 1.7.0 now supports extended props in resource labels, too! So now you can have custom html with custom data just like you can with events, the API is the same.

**Comment by lukacavic** [comment]
Great. Thanks

**Comment by aeq-dev** [comment]
Is it possible for resourceTimeGridDay label ?

**Comment by lukas-frey** [comment]
I don't know what you mean. Anywhere where you can access `resource`, you can also access extended props.
