### ISSUE TITLE
[Bug]:  wrong position of conextual menu

### ISSUE THREAD

**Issue by p3dro-docplanner** [GuavaCZ/calendar#25]
### What happened?

When im creating a new event, using dateclick event or date select, the contextual menu doent appears close to the mouse.

<img width="858" alt="Screenshot 2024-08-09 at 15 14 15" src="https://github.com/user-attachments/assets/73d13f2a-2fb1-46b4-93da-200a2ddfb633">

Only it is good when the screen is small

<img width="769" alt="Screenshot 2024-08-09 at 15 16 42" src="https://github.com/user-attachments/assets/40079482-796e-4f4b-8436-a56ec2758ca0">

### How to reproduce the bug

using the contextual menu feature, click in the calendar. The contextual menu appears in the wrong position.

### Package Version

2.0

### PHP Version

8.2

### Laravel Version

9

### Which operating systems does with happen with?

macOS

**Comment by lukas-frey** [comment]
You need to follow all steps in the installation (https://github.com/GuavaCZ/calendar?tab=readme-ov-file#installation)

- `php artisan filament:assets`
- create custom theme
- add the required package blade files to the custom theme's tailwind.config.js

**Comment by lukas-frey** [comment]
You're welcome
