### ISSUE TITLE
[Request]: Conditional extendedProps for event

### ISSUE THREAD

**Issue by danhvu02** [GuavaCZ/calendar#29]
### What feature would you like to add?

I have Course model and Session model. The relationship is course has many sessions.
I have a CourseCalendarWidget where I display all sessions for a specific course. Because I show this widget inside the view page of the course, so I don't have to add info about the course to extendedProps such as course_name, staff ...
Howerver, I have a MasterCalendarWidget where I display all sessions for all courses. In this page, I want to add props like course_name, staff, ... to the event
My question is inside toEvent() method, is it possible to have conditional extendedProps only when I needed?

**Comment by lukas-frey** [comment]
No not possible. You have two widgets, just filter out the unneeded props in the `getEvents` method of the widget.

**Comment by danhvu02** [comment]
The second option works for me. Thank you so much!!
