### ISSUE TITLE
[Question]: Set polling

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#34]
### What happened?

Hello,
I set     `protected static ?string $pollingInterval = '10s'; `to my CalendarWidget but it doesn't refresh, how could we refresh events ?

### How to reproduce the bug

-

### Package Version

1.6

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by lukas-frey** [comment]
The calendar doesn't support polling.

**Comment by aeq-dev** [comment]
Thanks for quick reply,
In fact I got the idea :)
