### ISSUE TITLE
[Request]: current date

### ISSUE THREAD

**Issue by mwagena** [GuavaCZ/calendar#43]
### What feature would you like to add?

Is there a way to get the current date from the Calendar instance? with for example a getDate() accessor?
Thanks in advance

**Comment by lukas-frey** [comment]
Hi, you can try using the onViewMount event and read the dates from the current view:

```php
protected bool $viewDidMountEnabled = true;

public function onViewDidMount(array $info = []): void {
    // Read the view object from the $info array here
}
```

**Comment by mwagena** [comment]
Hi,

Thanks for the reply,
I have tried that method but it doesn't update on prev / next events.

**Comment by lukas-frey** [comment]
Then you can try this:

https://github.com/GuavaCZ/calendar/issues/42#issuecomment-2422542797

**Comment by lukas-frey** [comment]
And another possibility is this:

```php

protected bool $eventAllUpdatedEnabled = true;

    public function onEventAllUpdated(array $info = []): void {}
```

**Comment by mwagena** [comment]
hi, I ended up using onEventAllUpdated storing the info in a session to use it later in a 'duplicate day/week' action.
Thanks
