### ISSUE TITLE
[Bug]: Only dayGridMonth view able to show Events, while others view don't

### ISSUE THREAD

**Issue by keatliang2005** [GuavaCZ/calendar#50]
### What happened?

the package default view able to show events, but  using other view does not show any events at all 

default demo project view
<img width="960" alt="Screenshot 2024-12-10 at 4 01 58 PM" src="https://github.com/user-attachments/assets/4bda982d-472d-4285-8d31-d3844e0405ee">

### How to reproduce the bug

by using other view 

```php
protected string $calendarView = 'resourceTimeGridWeek';
```

after changing the view does not show any events.
<img width="956" alt="Screenshot 2024-12-10 at 4 03 34 PM" src="https://github.com/user-attachments/assets/73a1d15c-d91e-422f-9329-a2c9d54aea1e">

### Package Version

1.10.0

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by lukas-frey** [comment]
You're using resource time grid view, you need to add them to a resource for them to be visible.
