### ISSUE TITLE
[Request]: Timezone & Locale

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#8]
### What feature would you like to add?

Manage timezone & localization

**Comment by lukas-frey** [comment]
Hi, the underlaying vkurko/calendar package [doesn't support timezones.](https://github.com/vkurko/calendar/issues/215#issuecomment-1886436933).

To change the locale, in your widget class override the `$locale` property.

**Comment by xu2xulim** [comment]
@lukas-frey Would you be able to give some guidance on how to over the $locale property
