### ISSUE TITLE
[Request]: Set time interval

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#9]
### What feature would you like to add?

Ability to set working hours per day

**Comment by lukas-frey** [comment]
I'm not sure what you mean by that.

You can change a lot of options, even if not documented. Almost every [option vkurko/calendar supports](https://github.com/vkurko/calendar), you can set by overriding the `getOptions` method on the widget class.

If you want to change the times min/max time that the calendar shows, you can override the `getOptions` method and pass any option that vkurko/calendar supports:

```php
public function getOptions(): array
{
    return [
        'slotMinTime' => '08:00:00',
        'slotMaxTime' => '16:00:00'
    ];
}
```
This will only show time slots from 08:00 to 16:00 in the calendar.

**Comment by aeq-dev** [comment]
Yes ! this is what I mean :)))))) THANKS DEAR

**Comment by aeq-dev** [comment]
Yes ! this is what I mean :)))))) THANKS DEAR
